version: '3.8'
services:
  web:
    build: .
    ports:
      - "3002:5000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - DB_NAME=test
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network
  
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge